// packages/adapters/svelte/src/NotectlEditor.svelte
<script lang="ts">
  /**
   * Svelte component wrapper for NotectlEditor
   */

  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import { NotectlEditor as NotectlEditorCore } from '@notectl/core';
  import type { EditorConfig, EditorAPI } from '@notectl/core';

  // Props
  export let debug: boolean | undefined = undefined;
  export let content: string | object | undefined = undefined;
  export let placeholder: string | undefined = undefined;
  export let readOnly: boolean | undefined = undefined;
  export let accessibility: EditorConfig['accessibility'] | undefined = undefined;
  export let i18n: EditorConfig['i18n'] | undefined = undefined;
  export let theme: EditorConfig['theme'] | undefined = undefined;
  export let className: string = '';

  // Editor instance
  let containerRef: HTMLDivElement;
  let editor: NotectlEditorCore | null = null;

  // Event dispatcher
  const dispatch = createEventDispatcher<{
    contentChange: { content: unknown };
    selectionChange: { selection: unknown };
    focus: void;
    blur: void;
    ready: { editor: EditorAPI };
    error: { error: Error };
  }>();

  /**
   * Initialize editor
   */
  function initEditor() {
    if (!containerRef || editor) return;

    // Create editor instance
    editor = document.createElement('notectl-editor') as NotectlEditorCore;

    // Configure editor
    const config: EditorConfig = {
      debug,
      content,
      placeholder,
      readOnly,
      accessibility,
      i18n,
      theme,
    };
    editor.configure(config);

    // Attach event listeners
    editor.on('content-change', (data) => {
      dispatch('contentChange', { content: data.content });
    });

    editor.on('selection-change', (data) => {
      dispatch('selectionChange', { selection: data.selection });
    });

    editor.on('focus', () => {
      dispatch('focus');
    });

    editor.on('blur', () => {
      dispatch('blur');
    });

    editor.on('ready', () => {
      dispatch('ready', { editor: getEditorAPI() });
    });

    editor.on('error', (data) => {
      dispatch('error', { error: data.error });
    });

    // Mount editor
    containerRef.appendChild(editor);
  }

  /**
   * Destroy editor
   */
  function destroyEditor() {
    if (editor) {
      editor.destroy();
      if (containerRef?.contains(editor)) {
        containerRef.removeChild(editor);
      }
      editor = null;
    }
  }

  /**
   * Update editor configuration
   */
  function updateConfig() {
    if (!editor) return;

    const config: EditorConfig = {
      debug,
      content,
      placeholder,
      readOnly,
      accessibility,
      i18n,
      theme,
    };
    editor.configure(config);
  }

  /**
   * Get editor API
   */
  function getEditorAPI(): EditorAPI {
    if (!editor) {
      throw new Error('Editor not initialized');
    }
    return {
      getContent: () => editor!.getContent(),
      setContent: (content) => editor!.setContent(content),
      getState: () => editor!.getState(),
      executeCommand: (command, ...args) => editor!.executeCommand(command, ...args),
      registerPlugin: (plugin) => editor!.registerPlugin(plugin),
      unregisterPlugin: (pluginId) => editor!.unregisterPlugin(pluginId),
      destroy: () => editor!.destroy(),
    };
  }

  // Public API methods
  export function getContent(): unknown {
    return editor?.getContent();
  }

  export function setContent(newContent: unknown): void {
    editor?.setContent(newContent);
  }

  export function getState(): unknown {
    return editor?.getState();
  }

  export function executeCommand(command: string, ...args: unknown[]): void {
    editor?.executeCommand(command, ...args);
  }

  export function registerPlugin(plugin: unknown): void {
    editor?.registerPlugin(plugin);
  }

  export function unregisterPlugin(pluginId: string): void {
    editor?.unregisterPlugin(pluginId);
  }

  // Lifecycle
  onMount(() => {
    initEditor();
  });

  onDestroy(() => {
    destroyEditor();
  });

  // Reactive updates
  $: if (editor) {
    updateConfig();
  }
</script>

<div
  bind:this={containerRef}
  class={className}
  data-notectl-svelte-wrapper
/>

<style>
  div {
    display: block;
  }
</style>

// packages/adapters/react/src/NotectlEditor.tsx
/**
 * React component wrapper for NotectlEditor
 */

import React, { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';
import { NotectlEditor as NotectlEditorCore } from '@notectl/core';
import type { Document, EditorState } from '@notectl/core';

export interface NotectlEditorProps {
  /** Custom class name */
  className?: string;
  /** Custom style */
  style?: React.CSSProperties;
  /** On content change callback */
  onContentChange?: (state: EditorState) => void;
  /** On focus callback */
  onFocus?: () => void;
  /** On blur callback */
  onBlur?: () => void;
  /** Initial content as HTML */
  initialContent?: string;
  /** Placeholder text */
  placeholder?: string;
  /** Readonly mode */
  readonly?: boolean;
  /** Auto-focus on mount */
  autofocus?: boolean;
}

export interface NotectlEditorHandle {
  /** Get current editor state */
  getState: () => EditorState;
  /** Get document as JSON */
  getJSON: () => Document;
  /** Set document from JSON */
  setJSON: (doc: Document) => void;
  /** Get HTML content */
  getHTML: () => string;
  /** Set HTML content */
  setHTML: (html: string) => void;
  /** Set content from string */
  setContent: (content: string, allowHTML?: boolean) => void;
  /** Undo last change */
  undo: () => void;
  /** Redo last undone change */
  redo: () => void;
  /** Focus the editor */
  focus: () => void;
  /** Blur the editor */
  blur: () => void;
}

/**
 * NotectlEditor React component
 */
export const NotectlEditor = forwardRef<NotectlEditorHandle, NotectlEditorProps>(
  (props, ref) => {
    const {
      className,
      style,
      onContentChange,
      onFocus,
      onBlur,
      initialContent,
      placeholder,
      readonly,
      autofocus,
    } = props;

    const editorRef = useRef<NotectlEditorCore | null>(null);
    const containerRef = useRef<HTMLDivElement>(null);

    // Expose editor API to parent via ref
    useImperativeHandle(ref, () => {
      const editor = editorRef.current;
      if (!editor) {
        throw new Error('Editor not initialized');
      }
      return {
        getState: () => editor.getState(),
        getJSON: () => editor.getJSON(),
        setJSON: (doc: Document) => editor.setJSON(doc),
        getHTML: () => editor.getHTML(),
        setHTML: (html: string) => editor.setHTML(html),
        setContent: (content: string, allowHTML?: boolean) => editor.setContent(content, allowHTML),
        undo: () => editor.undo(),
        redo: () => editor.redo(),
        focus: () => editor.focus(),
        blur: () => editor.blur(),
      };
    }, []);

    useEffect(() => {
      if (!containerRef.current) return;

      // Create editor instance
      const editor = document.createElement('notectl-editor') as NotectlEditorCore;
      editorRef.current = editor;

      // Set attributes
      if (placeholder !== undefined) {
        editor.setAttribute('placeholder', placeholder);
      }
      if (readonly !== undefined && readonly) {
        editor.setAttribute('readonly', '');
      }
      if (autofocus !== undefined && autofocus) {
        editor.setAttribute('autofocus', '');
      }

      // Set initial content if provided
      if (initialContent !== undefined) {
        editor.setHTML(initialContent);
      }

      // Attach event listeners
      const handleChange = (data: any) => {
        if (onContentChange) {
          onContentChange(data.state);
        }
      };
      const handleFocus = () => {
        if (onFocus) {
          onFocus();
        }
      };
      const handleBlur = () => {
        if (onBlur) {
          onBlur();
        }
      };

      editor.on('change', handleChange);
      editor.on('focus', handleFocus);
      editor.on('blur', handleBlur);

      // Mount editor
      containerRef.current.appendChild(editor);

      // Cleanup
      return () => {
        if (containerRef.current?.contains(editor)) {
          containerRef.current.removeChild(editor);
        }
        editorRef.current = null;
      };
    }, []);

    // Update placeholder when it changes
    useEffect(() => {
      if (editorRef.current && placeholder !== undefined) {
        editorRef.current.setAttribute('placeholder', placeholder);
      }
    }, [placeholder]);

    // Update readonly when it changes
    useEffect(() => {
      if (editorRef.current && readonly !== undefined) {
        if (readonly) {
          editorRef.current.setAttribute('readonly', '');
        } else {
          editorRef.current.removeAttribute('readonly');
        }
      }
    }, [readonly]);

    return (
      <div
        ref={containerRef}
        className={className as string | undefined}
        style={style as React.CSSProperties | undefined}
        data-notectl-react-wrapper
      />
    );
  }
);

NotectlEditor.displayName = 'NotectlEditor';
